# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'TheSmileyApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'GoogleMaps' #,'= 2.4'
  #pod 'Google-Maps-iOS-Utils'
  
  # Pods for TheSmileyApp
  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 4.5'
end
